blockchain:
  etherscan:
    ethereum-mainnet:
      network: mainnet
      apiKey: ${ETHERSCAN_API_KEY}
    ethereum-goerli:
      network: goerli
      apiKey: ${ETHERSCAN_API_KEY}
    aurora-mainnet:
      network: aurora
      apiKey: ${AURORASCAN_API_KEY}
catalog:
  locations:
    # Aurora Engine components
    - type: url
      target: https://github.com/aurora-is-near/aurora-engine/blob/develop/.catalog-info.yaml
    # Fast Bridge components
    - type: url
      target: https://github.com/aurora-is-near/fast-bridge-protocol/blob/master/.catalog-info.yaml
