blockchain:
  etherscan:
    ethereum-mainnet:
      network: mainnet
      apiKey: ${ETHERSCAN_API_KEY}
    ethereum-goerli:
      network: goerli
      apiKey: ${ETHERSCAN_API_KEY}
    aurora-mainnet:
      network: aurora
      apiKey: ${AURORASCAN_API_KEY}
  nearblocks:
    requestsPerSecond: 2
    apiKey: ${NEAR_BLOCKS_API_KEY}
catalog:
  locations:
    # Aurora Engine components
    - type: url
      target: https://github.com/aurora-is-near/aurora-engine/blob/develop/.catalog-info.yaml
    # Omni Bridge components
    - type: url
      target: https://github.com/Near-One/omni-bridge/blob/main/.catalog-info.yaml
    # Near Intents components
    - type: url
      target: https://github.com/near/intents/blob/main/.catalog-info.yaml
